import { 
  StudentProfile, 
  StudyCircle, 
  BountyQuestion, 
  PeerReview, 
  ChatConversation, 
  OrganizerNotice, 
  SkillCertificate,
  SkillSwapRequest,
  MentorshipSession
} from './types';

export const UNIVERSITY_NAME = "Ratan Tata Maharashtra State Skills University (RTMSSU)";
export const UNIVERSITY_SHORT = "RTMSSU";

// MULTIPLE DEMO USERS FOR ALL ROLES
export const DEMO_USERS: Record<string, StudentProfile> = {
  // Students
  'student-grishma': {
    id: 'user-grishma',
    name: 'Grishma Patil',
    email: 'grishma.patil@rtmssu.ac.in',
    prn: 'RTMSSU-23-DS-014',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Grishma&backgroundColor=ffdfbf',
    university: UNIVERSITY_NAME,
    department: 'School of Emerging Technologies',
    major: 'B.Tech Data Science & AI (3rd Year)',
    year: 'Junior 3rd Year',
    bio: 'Data Science & Machine Learning enthusiast at RTMSSU. Working on predictive modeling, Python data pipelines, and PyTorch. Looking to trade Python & Statistics mentorship for React frontend and Cloud DevOps guidance.',
    rating: 4.96,
    reviewCount: 19,
    hoursTaught: 28,
    skillsOffered: [
      { name: 'Python & Pandas', category: 'tech', level: 'Advanced' },
      { name: 'PyTorch Basics', category: 'tech', level: 'Intermediate' },
      { name: 'Exploratory Data Analysis', category: 'tech', level: 'Advanced' },
      { name: 'Applied Statistics', category: 'math', level: 'Advanced' },
    ],
    skillsWanted: ['React & Vite', 'Docker & Kubernetes', 'Tailwind CSS', 'System Design'],
    availability: 'Mon, Wed, Fri 4:30 - 7:30 PM (Campus Lab 2 / Online)',
    verifiedStudent: true,
    online: true,
  },
  'student-bhagyesh': {
    id: 'user-bhagyesh',
    name: 'Bhagyesh Nerkar',
    email: 'bhagyesh.nerkar@rtmssu.ac.in',
    prn: 'RTMSSU-23-CE-042',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=bhagyesh&backgroundColor=1e3a8a',
    university: UNIVERSITY_NAME,
    department: 'School of Engineering & Smart Technologies',
    major: 'B.Tech Computer Engineering (Final Year)',
    year: 'Final Year Senior',
    bio: 'Full-stack web engineer and Linux geek. Experienced with React, TypeScript, and microservice APIs. Looking to barter frontend architectural mentorship for Discrete Mathematics & DSA problem solving.',
    rating: 4.94,
    reviewCount: 22,
    hoursTaught: 36,
    skillsOffered: [
      { name: 'React & Vite', category: 'tech', level: 'Advanced' },
      { name: 'TypeScript', category: 'tech', level: 'Advanced' },
      { name: 'Tailwind CSS', category: 'tech', level: 'Advanced' },
      { name: 'Node.js & Express', category: 'tech', level: 'Intermediate' },
    ],
    skillsWanted: ['Data Structures & Algorithms', 'Linear Algebra', 'Computer Vision'],
    availability: 'Tue, Thu 5:00 - 8:00 PM & Weekends',
    verifiedStudent: true,
    online: true,
  },
  'student-snehal': {
    id: 'user-snehal',
    name: 'Snehal Gaikwad',
    email: 'snehal.gaikwad@rtmssu.ac.in',
    prn: 'RTMSSU-24-DE-009',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Snehal&backgroundColor=ffd5dc',
    university: UNIVERSITY_NAME,
    department: 'School of Design & Media Technologies',
    major: 'B.Des Interaction & Product Design (2nd Year)',
    year: 'Sophomore 2nd Year',
    bio: 'Lead student designer for RTMSSU campus publications. I teach design tokens, Figma auto-layouts, wireframing, and usability heuristics. Looking for Python & automation mentors.',
    rating: 4.88,
    reviewCount: 15,
    hoursTaught: 21,
    skillsOffered: [
      { name: 'Figma & Design Systems', category: 'design', level: 'Advanced' },
      { name: 'Wireframing & UI Critiques', category: 'design', level: 'Advanced' },
      { name: 'Design Tokens', category: 'design', level: 'Intermediate' },
    ],
    skillsWanted: ['Python for Automation', 'Next.js', 'Frontend Development'],
    availability: 'Wed, Fri 3:00 - 6:00 PM',
    verifiedStudent: true,
    online: false,
  },
  'student-aniket': {
    id: 'user-aniket',
    name: 'Aniket More',
    email: 'aniket.more@rtmssu.ac.in',
    prn: 'RTMSSU-23-FT-031',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aniket&backgroundColor=d1f4d9',
    university: UNIVERSITY_NAME,
    department: 'School of Management & Entrepreneurship',
    major: 'B.Tech FinTech & Smart Contracts',
    year: 'Junior 3rd Year',
    bio: 'Building decentralized ledger prototypes and Go backend services. Interested in exchanging Go systems programming and financial modeling for product design & React.',
    rating: 4.82,
    reviewCount: 12,
    hoursTaught: 18,
    skillsOffered: [
      { name: 'Go & REST APIs', category: 'tech', level: 'Advanced' },
      { name: 'Financial Modeling', category: 'business', level: 'Intermediate' },
      { name: 'SQL & Database Design', category: 'tech', level: 'Intermediate' },
    ],
    skillsWanted: ['Figma UI Prototyping', 'React Components', 'Pitch Decks'],
    availability: 'Mon, Thu 6:00 - 8:30 PM',
    verifiedStudent: true,
    online: true,
  },

  // Mentors
  'mentor-tanvi': {
    id: 'mentor-tanvi',
    name: 'Tanvi Deshmukh',
    email: 'tanvi.deshmukh@rtmssu.ac.in',
    prn: 'RTMSSU-22-AI-005',
    role: 'mentor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tanvi&backgroundColor=b6e3f4',
    university: UNIVERSITY_NAME,
    department: 'School of Emerging Technologies',
    major: 'M.Tech Artificial Intelligence & Deep Learning',
    year: 'Senior Peer Mentor (M.Tech Final Year)',
    bio: 'Lead peer mentor at RTMSSU AI Research Lab. Mentored over 45 students in Deep Learning, PyTorch, and NLP. Official evaluator for university skill certificates.',
    rating: 4.98,
    reviewCount: 42,
    hoursTaught: 64,
    skillsOffered: [
      { name: 'PyTorch & Deep Learning', category: 'tech', level: 'Advanced' },
      { name: 'Convolutional Neural Networks', category: 'tech', level: 'Advanced' },
      { name: 'Linear Algebra for ML', category: 'math', level: 'Advanced' },
      { name: 'Research Paper Writing', category: 'business', level: 'Advanced' },
    ],
    skillsWanted: ['Next.js Architecture', 'Cloud Infrastructure', 'Kubernetes'],
    availability: 'Daily 4:00 - 7:00 PM (RTMSSU AI Research Lab 3)',
    verifiedStudent: true,
    online: true,
    mentorOfficeHours: 'Mon, Wed, Fri 4:00 PM - 6:30 PM in RTMSSU AI Lab 3',
    mentorSlotsAvailable: 4,
  },
  'mentor-rohan': {
    id: 'mentor-rohan',
    name: 'Rohan Kulkarni',
    email: 'rohan.kulkarni@rtmssu.ac.in',
    prn: 'RTMSSU-22-CS-088',
    role: 'mentor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rohan&backgroundColor=d1d4f9',
    university: UNIVERSITY_NAME,
    department: 'School of Engineering & Smart Technologies',
    major: 'B.Tech Computer Engineering (4th Year)',
    year: 'Senior Coding Mentor',
    bio: 'President of RTMSSU Competitive Programming Club. Ranked top 1% nationally in university hackathons. Mentors in graph algorithms, advanced DP, and technical interview prep.',
    rating: 4.97,
    reviewCount: 38,
    hoursTaught: 58,
    skillsOffered: [
      { name: 'Data Structures & Algorithms', category: 'tech', level: 'Advanced' },
      { name: 'Graph Theory & DP', category: 'tech', level: 'Advanced' },
      { name: 'C++ Systems Architecture', category: 'tech', level: 'Advanced' },
    ],
    skillsWanted: ['Docker Swarm', 'AWS Cloud Solutions', 'Mobile App Dev'],
    availability: 'Tue, Thu after 5:30 PM & Sat All Day',
    verifiedStudent: true,
    online: true,
    mentorOfficeHours: 'Tue, Thu 6:00 PM - 8:00 PM at Lab 2',
    mentorSlotsAvailable: 3,
  },
  'mentor-aditya': {
    id: 'mentor-aditya',
    name: 'Aditya Joshi',
    email: 'aditya.joshi@rtmssu.ac.in',
    prn: 'RTMSSU-22-ME-052',
    role: 'mentor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aditya&backgroundColor=c0aede',
    university: UNIVERSITY_NAME,
    department: 'School of Engineering & Smart Technologies',
    major: 'B.Tech Robotics & Embedded Systems',
    year: 'Senior Peer Mentor',
    bio: 'Graduate teaching assistant in engineering mathematics and robotics kinematics. Passionate about simplifying complex proofs and mentoring students through NEP skill accreditation.',
    rating: 4.93,
    reviewCount: 29,
    hoursTaught: 44,
    skillsOffered: [
      { name: 'Multivariable Calculus', category: 'math', level: 'Advanced' },
      { name: 'Differential Equations', category: 'math', level: 'Advanced' },
      { name: 'Embedded C & Robotics', category: 'tech', level: 'Advanced' },
    ],
    skillsWanted: ['Python for Data Analysis', 'Git CI/CD', 'Computer Vision'],
    availability: 'Daily 5:00 - 8:00 PM',
    verifiedStudent: true,
    online: true,
    mentorOfficeHours: 'Mon, Wed 5:00 PM - 7:00 PM in Mechatronics Lab',
    mentorSlotsAvailable: 5,
  },

  // Organizers / Faculty
  'organizer-arvind': {
    id: 'organizer-arvind',
    name: 'Dr. Arvind Kulkarni',
    email: 'arvind.kulkarni@rtmssu.ac.in',
    prn: 'RTMSSU-FAC-008',
    role: 'organizer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ArvindKulkarni&backgroundColor=fed7aa',
    university: UNIVERSITY_NAME,
    department: 'Directorate of Student Innovation & Skill Competitions',
    major: 'Dean of Academic Skills & Innovation',
    year: 'Faculty Convener',
    bio: 'Dean of Student Innovation and Skill Development at RTMSSU. Overseeing the campus peer knowledge exchange, NEP skill-credit transfer governance, and university hackathons.',
    rating: 5.0,
    reviewCount: 95,
    hoursTaught: 120,
    skillsOffered: [
      { name: 'Academic Skill Accreditation', category: 'business', level: 'Advanced' },
      { name: 'NEP Policy Implementation', category: 'business', level: 'Advanced' },
    ],
    skillsWanted: [],
    availability: 'Campus Office: Mon-Fri 10:00 AM - 5:00 PM',
    verifiedStudent: true,
    online: true,
  },
  'organizer-sunita': {
    id: 'organizer-sunita',
    name: 'Prof. Sunita Deshpande',
    email: 'sunita.deshpande@rtmssu.ac.in',
    prn: 'RTMSSU-FAC-014',
    role: 'organizer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SunitaDeshpande&backgroundColor=e9d5ff',
    university: UNIVERSITY_NAME,
    department: 'Academic Affairs & Examination Council',
    major: 'Head of NEP Skill Transfer Credit Cell',
    year: 'Controller of Skill Accreditation',
    bio: 'Directing the examination and NEP academic credit audit cell at RTMSSU. Validating student peer tutoring logs for semester grade card integrations.',
    rating: 4.99,
    reviewCount: 80,
    hoursTaught: 90,
    skillsOffered: [
      { name: 'Curriculum & Credit Framework', category: 'business', level: 'Advanced' },
    ],
    skillsWanted: [],
    availability: 'Campus Office: Tue-Sat 9:30 AM - 4:30 PM',
    verifiedStudent: true,
    online: true,
  },
  'organizer-shantanu': {
    id: 'organizer-shantanu',
    name: 'Shantanu Shinde',
    email: 'shantanu.shinde@rtmssu.ac.in',
    prn: 'RTMSSU-FAC-021',
    role: 'organizer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ShantanuShinde&backgroundColor=bbf7d0',
    university: UNIVERSITY_NAME,
    department: 'Industry Relations & Hackathon Cell',
    major: 'Director of Hackathons & Corporate Partnerships',
    year: 'Industry Liaison Officer',
    bio: 'Connecting RTMSSU student innovators with industry hackathons, corporate problem statements, and startup pre-incubation grants across Maharashtra.',
    rating: 4.95,
    reviewCount: 65,
    hoursTaught: 75,
    skillsOffered: [
      { name: 'Industry Outreach', category: 'business', level: 'Advanced' },
      { name: 'Startup Incubation', category: 'business', level: 'Advanced' },
    ],
    skillsWanted: [],
    availability: 'Campus Office: Mon-Fri 11:00 AM - 6:00 PM',
    verifiedStudent: true,
    online: true,
  },
};

// Default Active User is Grishma Patil!
export const CURRENT_USER: StudentProfile = DEMO_USERS['student-grishma'];

// Public Peer Students catalog
export const INITIAL_STUDENTS: StudentProfile[] = [
  DEMO_USERS['mentor-tanvi'],
  DEMO_USERS['mentor-rohan'],
  DEMO_USERS['student-bhagyesh'],
  DEMO_USERS['student-snehal'],
  DEMO_USERS['mentor-aditya'],
  DEMO_USERS['student-aniket'],
  {
    id: 'student-sayali',
    name: 'Sayali Shinde',
    email: 'sayali.shinde@rtmssu.ac.in',
    prn: 'RTMSSU-23-AI-029',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sayali&backgroundColor=fed7aa',
    university: UNIVERSITY_NAME,
    department: 'School of Emerging Technologies',
    major: 'B.Tech AI & Robotics',
    year: 'Junior 3rd Year',
    bio: 'Conducting computer vision and image processing projects in Campus Lab 3. Excited to teach OpenCV and Python in return for React state management.',
    rating: 4.91,
    reviewCount: 17,
    hoursTaught: 26,
    skillsOffered: [
      { name: 'Computer Vision & OpenCV', category: 'tech', level: 'Advanced' },
      { name: 'Python NumPy & Scipy', category: 'tech', level: 'Advanced' },
      { name: 'Calculus III', category: 'math', level: 'Intermediate' },
    ],
    skillsWanted: ['React & Vite', 'Tailwind CSS', 'Figma Wireframes'],
    availability: 'Mon, Thu 4:00 - 7:00 PM',
    verifiedStudent: true,
    online: true,
  },
  {
    id: 'student-prathamesh',
    name: 'Prathamesh Sawant',
    email: 'prathamesh.sawant@rtmssu.ac.in',
    prn: 'RTMSSU-24-CS-062',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Prathamesh&backgroundColor=bae6fd',
    university: UNIVERSITY_NAME,
    department: 'School of Engineering & Smart Technologies',
    major: 'B.Tech Computer Engineering',
    year: 'Sophomore 2nd Year',
    bio: 'Linux and network security fanatic. Building secure microservices and Docker containers. I teach Shell scripting and Linux systems in return for Calculus.',
    rating: 4.87,
    reviewCount: 14,
    hoursTaught: 19,
    skillsOffered: [
      { name: 'Linux System Admin & Bash', category: 'tech', level: 'Advanced' },
      { name: 'Docker & Containers', category: 'tech', level: 'Intermediate' },
      { name: 'Network Protocols', category: 'tech', level: 'Intermediate' },
    ],
    skillsWanted: ['Differential Equations', 'Linear Algebra', 'PyTorch'],
    availability: 'Wed, Sat 5:00 - 8:00 PM',
    verifiedStudent: true,
    online: true,
  },
  {
    id: 'student-vaidehi',
    name: 'Vaidehi Kadam',
    email: 'vaidehi.kadam@rtmssu.ac.in',
    prn: 'RTMSSU-24-LG-011',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vaidehi&backgroundColor=fbcfe8',
    university: UNIVERSITY_NAME,
    department: 'School of Skill Development & Humanities',
    major: 'B.A. Technical Communication & Foreign Languages',
    year: 'Junior 3rd Year',
    bio: 'Certified corporate communication coach and Japanese JLPT N2 holder at RTMSSU. I host pitch coaching and conversational Japanese. Seeking SQL & database guidance.',
    rating: 5.0,
    reviewCount: 23,
    hoursTaught: 35,
    skillsOffered: [
      { name: 'Corporate Presentation & Pitching', category: 'business', level: 'Advanced' },
      { name: 'Conversational Japanese (JLPT)', category: 'language', level: 'Advanced' },
      { name: 'Technical Documentation', category: 'language', level: 'Advanced' },
    ],
    skillsWanted: ['SQL & PostgreSQL', 'Database Modeling', 'Python'],
    availability: 'Saturday & Sunday Mornings',
    verifiedStudent: true,
    online: false,
  },
];

export const INITIAL_STUDY_CIRCLES: StudyCircle[] = [
  {
    id: 'circle-1',
    title: 'RTMSSU Coding Club: Placement DSA & Graph Algorithms',
    category: 'Computer Engineering',
    description: 'Daily peer problem-solving in Campus Lab 2. Tackling graph algorithms, dynamic programming, and mock technical interview rounds for upcoming campus placements.',
    hostName: 'Rohan Kulkarni',
    hostAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rohan&backgroundColor=d1d4f9',
    hostUniversity: UNIVERSITY_NAME,
    maxCapacity: 8,
    currentFocusTopic: 'Graph Shortest Paths & Dijkstra vs A*',
    tags: ['Algorithms', 'Campus Placements', 'LeetCode', 'C++/Java'],
    isLive: true,
    activeParticipants: [
      { id: 'p1', name: 'Rohan Kulkarni (Host)', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rohan', role: 'host', status: 'Screen Sharing', micOn: true },
      { id: 'p2', name: 'Tanvi Deshmukh', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tanvi', role: 'member', status: 'Focusing', micOn: false },
      { id: 'p3', name: 'Grishma (You)', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Grishma', role: 'member', status: 'Focusing', micOn: false },
      { id: 'p4', name: 'Bhagyesh Nerkar', avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=bhagyesh', role: 'member', status: 'Taking Break', micOn: false },
    ],
  },
  {
    id: 'circle-2',
    title: 'RTMSSU AI Research Lab: Neural Net Architectures Pod',
    category: 'School of Emerging Technologies',
    description: 'Collaborative study pod in Campus AI Lab 3. Reviewing PyTorch training loops, loss convergence, and attention mechanism mathematics.',
    hostName: 'Tanvi Deshmukh',
    hostAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tanvi&backgroundColor=b6e3f4',
    hostUniversity: UNIVERSITY_NAME,
    maxCapacity: 10,
    currentFocusTopic: 'PyTorch Multi-GPU Distributed Training & Loss Tuning',
    tags: ['Machine Learning', 'PyTorch', 'Research', 'Lab 3'],
    isLive: true,
    activeParticipants: [
      { id: 'p5', name: 'Tanvi Deshmukh (Host)', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tanvi', role: 'host', status: 'Helping', micOn: true },
      { id: 'p6', name: 'Grishma Patil', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Grishma', role: 'member', status: 'Focusing', micOn: true },
      { id: 'p7', name: 'Aditya Joshi', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aditya', role: 'member', status: 'Focusing', micOn: false },
    ],
  },
  {
    id: 'circle-3',
    title: 'Engineering Mathematics & Derivations Desk',
    category: 'Engineering Sciences',
    description: 'Working through tutorial sheets on eigenvalues, multivariable gradient vectors, and Taylor series with step-by-step proofs for upcoming semester exams.',
    hostName: 'Aditya Joshi',
    hostAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aditya&backgroundColor=c0aede',
    hostUniversity: UNIVERSITY_NAME,
    maxCapacity: 6,
    currentFocusTopic: 'Eigenvalue decomposition & Principal Component Analysis intuition',
    tags: ['Math Semester III', 'Calculus', 'Linear Algebra', 'Exam Prep'],
    isLive: true,
    activeParticipants: [
      { id: 'p8', name: 'Aditya Joshi (Host)', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aditya', role: 'host', status: 'Screen Sharing', micOn: true },
      { id: 'p9', name: 'Prathamesh Sawant', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Prathamesh', role: 'member', status: 'Focusing', micOn: false },
    ],
  },
];

export const INITIAL_BOUNTIES: BountyQuestion[] = [
  {
    id: 'bounty-1',
    title: 'How to fix shape mismatch in PyTorch cross-entropy loss with 2D tensor?',
    description: "In our RTMSSU AI lab project, I am passing logits of shape `[batch_size, num_classes]` and targets of shape `[batch_size, 1]`, and getting `RuntimeError: 1D target tensor expected, multi-target not supported`. What is the cleanest way to reshape without unnecessary copies?",
    codeSnippet: `criterion = nn.CrossEntropyLoss()
logits = model(images) # shape: torch.Size([32, 10])
targets = labels       # shape: torch.Size([32, 1])
loss = criterion(logits, targets) # throws RuntimeError`,
    authorName: 'Siddharth Patil',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Siddharth',
    authorUniversity: UNIVERSITY_NAME,
    bountyCredits: 3,
    tags: ['PyTorch', 'RTMSSU AI Lab', 'Python', 'Tensors'],
    category: 'tech',
    createdAt: '35 mins ago',
    status: 'open',
    answers: [
      {
        id: 'ans-1',
        authorName: 'Tanvi Deshmukh',
        authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tanvi',
        authorUniversity: UNIVERSITY_NAME,
        content: "PyTorch's `CrossEntropyLoss` expects targets to be a 1D tensor of class indices `[N]` with data type `torch.long`, not a 2D column vector `[N, 1]`. Simply use `.squeeze(1)` or `.view(-1)` along with `.long()`.",
        codeSnippet: `loss = criterion(logits, targets.squeeze(1).long())`,
        createdAt: '20 mins ago',
        upvotes: 6,
        isAccepted: false,
      },
    ],
  },
  {
    id: 'bounty-2',
    title: 'Intuitive geometric explanation for why SVD works on any rectangular matrix?',
    description: "Preparing for our RTMSSU Linear Algebra mid-semester exam. I understand eigenvalue decomposition for square diagonalizable matrices, but why is Singular Value Decomposition guaranteed for any m x n matrix? How do orthonormal bases transform into another orthonormal set through ellipses?",
    authorName: 'Pooja Deshmukh',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pooja',
    authorUniversity: UNIVERSITY_NAME,
    bountyCredits: 4,
    tags: ['Linear Algebra', 'SVD', 'Exam Prep', 'Mathematics'],
    category: 'math',
    createdAt: '2 hours ago',
    status: 'open',
    answers: [
      {
        id: 'ans-2',
        authorName: 'Aditya Joshi',
        authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aditya',
        authorUniversity: UNIVERSITY_NAME,
        content: "Think of any linear transformation as mapping a unit sphere in R^n to a hyper-ellipse in R^m. The principal axes of that ellipse are mutually orthogonal! The unit vectors along the original axes that land on those principal axes form the orthonormal basis V, the stretch factors are the singular values Σ, and the unit vectors along the ellipse axes form U. Thus A = U Σ V^T!",
        createdAt: '1 hour ago',
        upvotes: 11,
        isAccepted: true,
      },
    ],
  },
];

export const MOCK_REVIEWS: PeerReview[] = [
  {
    id: 'rev-1',
    reviewerName: 'Tanvi Deshmukh',
    reviewerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tanvi',
    reviewerUniversity: UNIVERSITY_NAME,
    skillTaught: 'Python & Pandas',
    skillReceived: 'PyTorch & Neural Networks',
    rating: 5,
    comment: 'Grishma explained data cleaning and vectorization techniques with exceptional clarity! She helped refactor our research dataset pipeline in RTMSSU Lab 3, speeding up our model training drastically.',
    date: '2 days ago',
  },
  {
    id: 'rev-2',
    reviewerName: 'Rohan Kulkarni',
    reviewerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rohan',
    reviewerUniversity: UNIVERSITY_NAME,
    skillTaught: 'Statistical Modeling',
    skillReceived: 'Graph Algorithms',
    rating: 5,
    comment: 'Great peer exchange. Grishma broke down probability density functions and hypotheses tests, while I coached her on dynamic programming. Super productive!',
    date: '1 week ago',
  },
  {
    id: 'rev-3',
    reviewerName: 'Snehal Gaikwad',
    reviewerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Snehal',
    reviewerUniversity: UNIVERSITY_NAME,
    skillTaught: 'Data Visualization (Seaborn)',
    skillReceived: 'Figma Design Tokens',
    rating: 5,
    comment: 'Brilliant barter session. We mapped data charts into our Figma prototype in under 45 minutes.',
    date: '2 weeks ago',
  },
];

export const INITIAL_CONVERSATIONS: ChatConversation[] = [
  {
    id: 'conv-1',
    partner: DEMO_USERS['mentor-tanvi'],
    lastMessage: 'Great, see you on Wednesday at 4:30 PM in RTMSSU AI Lab 3 for our Pandas <-> PyTorch session!',
    lastTimestamp: '11:15 AM',
    unreadCount: 0,
    nextSession: {
      date: 'Wed, Oct 1st · 4:30 PM (Campus Lab 3)',
      topic: 'Vectorized Pandas feature extraction ↔ PyTorch DataLoader GPU optimization',
      duration: '60 minutes (30m Data / 30m PyTorch)',
    },
    sharedNotes: `### RTMSSU Skill Barter Agenda:
1. 00-30m: Grishma demonstrates memory-efficient Pandas vectorization for large datasets.
2. 30-60m: Tanvi walks through PyTorch batch DataLoader optimization on RTMSSU cluster.

### Campus Lab Coordinates:
- Lab: RTMSSU School of Emerging Tech, 2nd Floor, Room 204
- Cluster node: cluster.rtmssu.ac.in`,
    messages: [
      {
        id: 'm1',
        senderId: 'mentor-tanvi',
        senderName: 'Tanvi Deshmukh',
        text: 'Hi Grishma! I noticed your profile on RTMSSU Skill Swap. I saw you specialize in Pandas and exploratory analysis. I could really use a session to optimize our research dataset!',
        timestamp: 'Yesterday 3:15 PM',
        isMe: false,
      },
      {
        id: 'm2',
        senderId: 'user-grishma',
        senderName: 'Grishma Patil',
        text: "Hi Tanvi! I'd love to swap hours! In return, I am eager to learn PyTorch CNN training loops from you.",
        timestamp: 'Yesterday 3:28 PM',
        isMe: true,
      },
      {
        id: 'm3',
        senderId: 'mentor-tanvi',
        senderName: 'Tanvi Deshmukh',
        text: 'Perfect! Shall we meet Wednesday at 4:30 PM in Lab 3? I have booked our mentor co-working desk.',
        timestamp: 'Yesterday 3:40 PM',
        isMe: false,
      },
      {
        id: 'm4',
        senderId: 'user-grishma',
        senderName: 'Grishma Patil',
        text: 'Confirmed on the schedule! Looking forward to it.',
        timestamp: '11:00 AM',
        isMe: true,
      },
      {
        id: 'm5',
        senderId: 'mentor-tanvi',
        senderName: 'Tanvi Deshmukh',
        text: 'Great, see you on Wednesday at 4:30 PM in RTMSSU AI Lab 3 for our Pandas <-> PyTorch session!',
        timestamp: '11:15 AM',
        isMe: false,
      },
    ],
  },
  {
    id: 'conv-2',
    partner: DEMO_USERS['mentor-rohan'],
    lastMessage: 'Looking forward to reviewing your recursive tree solutions before the weekend mock test.',
    lastTimestamp: 'Yesterday',
    unreadCount: 1,
    sharedNotes: `Rohan's Recommended Problems:
- LC 104: Maximum Depth of Binary Tree
- LC 543: Diameter of Binary Tree
- LC 124: Binary Tree Maximum Path Sum`,
    messages: [
      {
        id: 'm6',
        senderId: 'mentor-rohan',
        senderName: 'Rohan Kulkarni',
        text: 'Hey Grishma! Thanks for helping out with the probability distributions in our coding group yesterday.',
        timestamp: 'Yesterday 2:10 PM',
        isMe: false,
      },
      {
        id: 'm7',
        senderId: 'mentor-rohan',
        senderName: 'Rohan Kulkarni',
        text: 'Looking forward to reviewing your recursive tree solutions before the weekend mock test.',
        timestamp: 'Yesterday 2:12 PM',
        isMe: false,
      },
    ],
  },
];

export const INITIAL_ORGANIZER_NOTICES: OrganizerNotice[] = [
  {
    id: 'notice-1',
    title: 'RTMSSU State Skills & Innovation Hackathon 2026',
    type: 'hackathon',
    organizerName: 'Dr. Arvind Kulkarni',
    organizerRole: 'Dean of Student Innovation & Skill Competitions',
    department: 'Directorate of Student Affairs, RTMSSU',
    description: '36-hour flagship state university hackathon open exclusively to RTMSSU students across all schools. Build real-world solutions for Smart Manufacturing, AI & Healthcare, FinTech, and Green Urban Mobility. Teams of 2 to 4 students.',
    eventDate: 'Nov 14 - Nov 16, 2026',
    deadline: 'Oct 30, 2026 · 11:59 PM',
    venueOrLink: 'RTMSSU Main Auditorium & Innovation Hub',
    tags: ['Hackathon', 'State Level', 'Cash Prize', 'All Departments', 'Incubation'],
    postedDate: 'Yesterday',
    prizesOrIncentive: '₹2,50,000 Total Prize Pool + Pre-Incubation Grant',
    eligibleBatches: 'All Undergraduate & Postgraduate Batches',
    registeredCount: 48,
    isUrgent: true,
  },
  {
    id: 'notice-2',
    title: 'End-Semester Capstone Project Phase-II Evaluation & Demonstration Schedule',
    type: 'exam',
    organizerName: 'Prof. Sunita Deshpande',
    organizerRole: 'Controller of Examinations & NEP Credit Auditor',
    department: 'Academic Affairs & Examination Council',
    description: 'Official schedule for Final Year B.Tech and M.Tech Capstone Project reviews. All student teams must present their working code, architecture documentation, and peer skill barter logbook. External industry evaluators will be present.',
    eventDate: 'Dec 02 - Dec 06, 2026',
    deadline: 'Nov 20, 2026 (Report Submission)',
    venueOrLink: 'Seminar Hall 1 & 2, RTMSSU Campus',
    tags: ['Exam Schedule', 'Capstone Evaluation', 'Final Year', 'Mandatory'],
    postedDate: '2 days ago',
    eligibleBatches: 'Final Year B.Tech & Final Year M.Tech',
    registeredCount: 120,
    isUrgent: true,
  },
  {
    id: 'notice-3',
    title: 'Skill Campaign: NVIDIA Deep Learning & Cloud Certification Accelerator',
    type: 'campaign',
    organizerName: 'Shantanu Shinde',
    organizerRole: 'Director of Hackathons & Corporate Partnerships',
    department: 'Industry Relations & Hackathon Cell',
    description: 'Comprehensive 4-week hybrid skill training campaign covering PyTorch, CUDA fundamentals, and Cloud Model Deployment. Certified by NVIDIA DLI & RTMSSU. 100% sponsored for registered RTMSSU students.',
    eventDate: 'Oct 15 - Nov 10, 2026',
    deadline: 'Oct 10, 2026',
    venueOrLink: 'Virtual Lectures + Hands-on in RTMSSU AI Lab',
    tags: ['Certification', 'NVIDIA', 'Deep Learning', 'Industry Sponsored'],
    postedDate: '3 days ago',
    prizesOrIncentive: 'Global Industry Certification Voucher + 4 Skill Credits',
    eligibleBatches: '2nd, 3rd & Final Year Students',
    registeredCount: 86,
    isUrgent: false,
  },
  {
    id: 'notice-4',
    title: 'Official Circular: Academic Skill Credits for Peer Mentorship on Skill Swap',
    type: 'announcement',
    organizerName: 'Dr. Arvind Kulkarni',
    organizerRole: 'Dean of Academic Skills & Innovation',
    department: 'Ratan Tata Maharashtra State Skills University (RTMSSU)',
    description: 'In accordance with National Education Policy (NEP) skill-credit framework, active students who mentor peers for 25+ verified hours on the Skill Swap platform are eligible for 2 Non-Academic Skill Transfer Credits in their semester marksheets.',
    deadline: 'End of Academic Year 2026-27',
    venueOrLink: 'Academic Portal: marksheet.rtmssu.ac.in',
    tags: ['Official Policy', 'NEP 2020', 'Academic Credits', 'Skill Transfer'],
    postedDate: '5 days ago',
    eligibleBatches: 'All Enrolled RTMSSU Students',
    registeredCount: 215,
    isUrgent: false,
  },
];

export const INITIAL_CERTIFICATES: SkillCertificate[] = [
  {
    id: 'cert-1',
    certificateNumber: 'RTMSSU-SKILL-2026-0914',
    studentName: 'Grishma Patil',
    studentPRN: 'RTMSSU-23-DS-014',
    studentEmail: 'grishma.patil@rtmssu.ac.in',
    skillName: 'Neural Networks & PyTorch Foundations',
    skillCategory: 'Artificial Intelligence & Neural Networks',
    mentorName: 'Tanvi Deshmukh',
    mentorPRN: 'RTMSSU-22-AI-005',
    hoursCompleted: 16,
    issueDate: 'September 18, 2026',
    university: UNIVERSITY_NAME,
    learningOutcomes: [
      'Mastered PyTorch Tensor manipulation, GPU memory pinning, and autograd mechanics',
      'Constructed modular neural network architectures with custom loss functions',
      'Completed verified peer-to-peer code review and lab projects under mentor supervision',
      'Demonstrated working predictive model artifact at RTMSSU Emerging Tech showcase'
    ],
    signatureAuthority: 'Dr. Arvind Kulkarni, Dean of Student Innovation & Skills',
    status: 'endorsed',
  },
  {
    id: 'cert-2',
    certificateNumber: 'RTMSSU-SKILL-2026-0742',
    studentName: 'Grishma Patil',
    studentPRN: 'RTMSSU-23-DS-014',
    studentEmail: 'grishma.patil@rtmssu.ac.in',
    skillName: 'Graph Algorithms & State Space Search',
    skillCategory: 'Computer Science & Algorithmics',
    mentorName: 'Rohan Kulkarni',
    mentorPRN: 'RTMSSU-22-CS-088',
    hoursCompleted: 14,
    issueDate: 'August 24, 2026',
    university: UNIVERSITY_NAME,
    learningOutcomes: [
      'Implemented Breadth-First Search, Depth-First Search, and Dijkstra shortest paths',
      'Derived asymptotic time complexities for connected component graph traversals',
      'Completed peer mock interview rounds at RTMSSU Coding Club'
    ],
    signatureAuthority: 'Prof. Sunita Deshpande, Head of Skill Accreditation',
    status: 'endorsed',
  },
];

// Mentor-specific mock requests & sessions
export const INITIAL_MENTOR_REQUESTS: SkillSwapRequest[] = [
  {
    id: 'req-1',
    fromStudentId: 'student-bhagyesh',
    fromStudentName: 'Bhagyesh Nerkar',
    fromStudentPRN: 'RTMSSU-23-CE-042',
    fromStudentAvatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=bhagyesh&backgroundColor=1e3a8a',
    fromStudentMajor: 'B.Tech Computer Engineering (Final Year)',
    toStudentId: 'mentor-tanvi',
    skillOffered: 'React & Vite Dashboard Architecture',
    skillRequested: 'PyTorch CUDA Memory Optimization',
    status: 'pending',
    scheduledTime: 'Thursday · 5:30 PM (Campus Lab 3)',
    sessionFormat: '60min',
    notes: 'Working on capstone project frontend and looking to exchange UI code reviews for GPU optimization tips.',
    createdAt: '2 hours ago',
  },
  {
    id: 'req-2',
    fromStudentId: 'student-snehal',
    fromStudentName: 'Snehal Gaikwad',
    fromStudentPRN: 'RTMSSU-24-DE-009',
    fromStudentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Snehal&backgroundColor=ffd5dc',
    fromStudentMajor: 'B.Des Interaction Design (2nd Year)',
    toStudentId: 'mentor-tanvi',
    skillOffered: 'Design Tokens & Figma Auto-Layout',
    skillRequested: 'Python Data Extraction for Designers',
    status: 'pending',
    scheduledTime: 'Friday · 4:00 PM (Design Studio 1)',
    sessionFormat: '30min',
    notes: 'Need guidance extracting survey data via Python scripts in exchange for design system setup.',
    createdAt: '5 hours ago',
  },
];

export const INITIAL_MENTOR_SESSIONS: MentorshipSession[] = [
  {
    id: 'session-1',
    mentorId: 'mentor-tanvi',
    menteeName: 'Grishma Patil',
    menteePRN: 'RTMSSU-23-DS-014',
    menteeAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Grishma',
    topic: 'Pandas Vectorization ↔ PyTorch DataLoader Tuning',
    scheduledTime: 'Wed, Oct 1 · 4:30 PM',
    durationMinutes: 60,
    location: 'RTMSSU AI Research Lab 3, Desk 4',
    status: 'scheduled',
    nepCreditsApplied: true,
    notes: 'Mutual 1-hour swap. Grishma shares Pandas tips; Tanvi covers PyTorch batch optimization.',
  },
  {
    id: 'session-2',
    mentorId: 'mentor-tanvi',
    menteeName: 'Aniket More',
    menteePRN: 'RTMSSU-23-FT-031',
    menteeAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aniket',
    topic: 'Time-Series Forecasting Models in PyTorch',
    scheduledTime: 'Mon, Sep 29 · 5:00 PM',
    durationMinutes: 45,
    location: 'Campus Virtual Lab Intranet',
    status: 'completed',
    nepCreditsApplied: true,
    notes: 'Covered LSTM model gates, sequence padding, and validation loss tracking.',
  },
];
